# <center>Arrays for Scientific Computation</center>
References:
* Numpy Quickstart Tutorial: https://docs.scipy.org/doc/numpy-1.14.0/user/quickstart.html
* Numpy Tutorial: http://cs231n.github.io/python-numpy-tutorial/#numpy
* Broadcasting arrays in Numpy, https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/

## 1. Numpy
- Numpy is the core library for scientific computing in Python. It provides high-performance multidimensional array objects, and tools for working with these arrays. 

- A numpy **array** is a grid of values, usually of the same type, although technically you can store values of different types (this may complicate array operation). 
    - The number of dimensions is the **rank** of the array
    - The **shape** of an array is a tuple of integers giving the size of the array along each dimension
      * e.g. array([5, 2, 3]) has shape (3,) 
      * e.g. array([[5, 2, 3], [1,2,3]]) has shape (2,3)
    - Numpy arrays can be initialized from nested Python lists, and access elements using square brackets

In [2]:
# enable interactiveShell
# so that Jupyter will display variables or 
# unassigned output of a statement 
# without the need for a print statement
# interactive shell don't need prinnt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# import numpy package
import numpy as np


In [3]:
# Exercise 1.1. Initialize an array from list

# Create a rank 1 array
a = np.array([1, 2, 3])  

print ("1. data type:", type(a))

print("2. array shape, ",a.shape)
# Note, (3,) means a tuple with only one element, 
# to have a tuple with only one element, 
# the "," at the end is mandatory

# following the same indexing rule to access elements
print("3. the first element:", a[0])

# Change an element of the array
a[0] = 5                 
a

1. data type: <class 'numpy.ndarray'>
2. array shape,  (3,)
3. the first element: 1


array([5, 2, 3])

In [9]:
# Exercise 1.2. Create a rank 2 array from list of lists

b = np.array([[1,2,3],[4,5,6]])   
b

print ("1. b's shape:", b.shape) 

# an array with rank 2 can be sliced in each dimension 
print("2. value at (0,0): ", b[0, 0])
print("3. value at (1,2): ", b[1, 2])   


array([[1, 2, 3],
       [4, 5, 6]])

1. b's shape: (2, 3)
2. value at (0,0):  1
3. value at (1,2):  6


In [10]:
# Exercise 1.3. Create a rank 2 array of all zeros

a = np.zeros((2,2))  
a

array([[0., 0.],
       [0., 0.]])

In [11]:
# Exercise 1.4. Create a rank 2 array of all ones

b = np.ones((3,2))   
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Exercise 1.5. Create a constant array

c = np.full((2,2), 7) 
c

array([[7, 7],
       [7, 7]])

In [7]:
# Exercise 1.6. a 2x2 identity matrix

d = np.eye(2)        
d

array([[1., 0.],
       [0., 1.]])

In [41]:
# Exercise 1.7. # Create a matrix filled with random values

# uniform distributed random floats within [0, 1.0)
np.random.rand(2,2)  # shape (2,2)
np.random.random((2,2)) # shape (2,2)

# randint(low, high, size): random integer
np.random.randint(1, 6, (4,5))

np.random.seed(1);np.random.rand(2,2)

array([[0.20445225, 0.87811744],
       [0.02738759, 0.67046751]])

array([[0.4173048 , 0.55868983],
       [0.14038694, 0.19810149]])

array([[2, 2, 2, 2, 1],
       [5, 2, 1, 1, 4],
       [3, 2, 1, 4, 2],
       [2, 4, 5, 1, 2]])

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01]])

In [3]:
# randn(d0, d1, ...dn): random floats 
# from normal distribution with shape (d0,d1,..., dn)
# mean 0 variance 1

a = np.random.randn(1,3,2) # array with rank 3
a.shape
a
a[0]
a[:,1,1]

(1, 3, 2)

array([[[ 1.48452383, -0.0248064 ],
        [ 0.35999686, -1.17272166],
        [-0.740971  , -1.89597667]]])

array([[ 1.48452383, -0.0248064 ],
       [ 0.35999686, -1.17272166],
       [-0.740971  , -1.89597667]])

array([-1.17272166])

In [100]:
A = np.random.randn(1,3)
A
A = np.random.randn(3,1)
A
A = np.random.randn(3,)
A

array([[-0.08523683, -0.29460413,  0.7955637 ]])

array([[ 2.0679274 ],
       [-0.98423193],
       [ 0.34347093]])

array([-0.08874451,  0.15656603, -0.02949018])

In [3]:
# similar to python range
a = np.arange(6)                
a
b = np.arange(12).reshape(4, 3)     
b
c = np.arange(24).reshape(2, 3, 4)
c

array([0, 1, 2, 3, 4, 5])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 1.1. Array Slicing
 - **Similar to Python lists, numpy arrays can be sliced**. 
 - Since arrays may be multidimensional, you must **specify a slice for each dimension of the array**
 - **A slice of an array is a view into the same data**, so modifying it will modify the original array.

In [11]:
# Exercise 1.1.1 Get a specific row

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.shape

# get the first row
a[0]      # a[0,:] does the same too

# shape of the first row
a[0].shape


# loop through all rows
for idx,row in enumerate(a):
    print(idx, row)

# what if the array has shape (4,3,2)? 
# what is the shape of its first row?
c = np.arange(24).reshape(4,3,2)
c[0].shape

(3, 4)

array([1, 2, 3, 4])

(4,)

0 [1 2 3 4]
1 [5 6 7 8]
2 [ 9 10 11 12]


(3, 2)

In [3]:
# Exercise 1.1.2 Get a specific column

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# get the first column
column_1=a[:, 0]      
column_1

# shape of 1st column
# Notice that the 1st column has reduced rank. It's just one dimensional
column_1.shape

# Question: if array X has shape (4,3,2)
# what is the shape of X[:,0,:]?



array([1, 5, 9])

(3,)

(4, 2)

In [4]:
# Exercise 1.1.3 Get subarrays

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a
a.shape

# Use slicing to pull out the subarray 
# consisting of the first two rows
# and 2nd and 3rd columns 

b = a[0:2, 1:3]
b

# Question: if array X has shape (4,3,2)
# what is the shape of X[:,1:3,:]?
# what is the shape of X[:,1:3,1]?


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

(3, 4)

array([[2, 3],
       [6, 7]])

In [3]:
# Exercise 1.1.4 

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

# Q1. Get subset of "a" consisting of
#    the 1st & 3rd rows and
#    the 1st & 3rd columns
# Here the rows and columns are not continuous.


# Can you use: a[[0,2], [0,2]] ? See what you get.
a[[0,2], [0,2]]

# How to revise?





# Q2. get the last two rows and last two columns
a[-2:,-2:]

# Q3. Reverse the order of columns, 
#    i.e. the first column becomes the last
a[:,::-1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([ 1, 11])

array([[ 7,  8],
       [11, 12]])

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [49]:
# Exercise 1.1.5: Modify slice

# A slice of an array is **a view into the same data**, 
# so modifying it will modify the original array.

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

# b is a slice
b = a[:2, 1:3]
print(b)

print ("1. Original value at (0,1):", a[0, 1])  
b[0, 0] = 77    

# b[0, 0] is the same piece of data as a[0, 1]
print ("2. Modified value at (0,1):", a[0, 1])  

# how to avoid modifying the original array? Use copy() function
b1=np.copy(b)
b1[0,0]=100
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

[[2 3]
 [6 7]]
1. Original value at (0,1): 2
2. Modified value at (0,1): 77


array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 1.2. Boolean array indexing (Selection by conditions)

- Boolean array indexing lets you pick out arbitrary elements of an array. 
- Frequently this type of indexing is used to select elements of an array that satisfy some conditions. 
- Typically it's used with function **np.where**

In [40]:
# Exercise 1.2.1: boolean array indexing

a = np.array([[1,2], [3, 4], [5, 6]])
a

# Find the elements of "a" that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where value tells
# whether that element of a is > 2

bool_idx = (a > 2)  

bool_idx

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [41]:
# Exercise 1.2.2: Select values >2

print (a[bool_idx])

# We can do all of the above in a single 
# concise statement:
print (a[a > 2])

# note the result is 1-dimension array

[3 4 5 6]
[3 4 5 6]


In [31]:
# Exercise 1.2.3: Find locations where value>2

a = np.array([[1,2], [3, 4], [5, 6]])

# np.where returns the locations satisfying the condition
# as a tuple of lists at one axis 

np.where(a>2)
# tuple 1st element gives you the index of axis 0, 2nd element gives you the index of axis 1
# which give you the corresponding location of four elements that satisfy the condition
a[np.where(a>2)]

(array([1, 1, 2, 2]), array([0, 1, 0, 1]))

array([3, 4, 5, 6])

In [48]:
# Exercise 1.2.4: change values by conditions

a = np.array([[4,2], [3, 4], [5, 0]])
print("1. Before change:", a)

# if a value >3, set it to 3
a[np.where(a>3)]=3

print("2. After change:", a)

# binarize the array, 
# if a value>3, set it to 1; otherwise, 0
a = np.array([[4,2], [3, 4], [5, 0]])
print("3. Binarized array:", np.where(a>3, 1, 0))


1. Before change: [[4 2]
 [3 4]
 [5 0]]
2. After change: [[3 2]
 [3 3]
 [3 0]]
3. Binarized array: [[1 0]
 [0 1]
 [1 0]]


### 1.3. Array Math

- Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module
- Pay attention to the difference between **elementwise product** and **dot product**

In [19]:
# Exercise 1.3.1: array addition

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [20]:
# Exercise 1.3.2: Subtraction

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [21]:
# Exercise 1.3.3:  Elementwise product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print (x * y)
print (np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [49]:
# Exercise 1.3.4:  dot product is matrix multiplication

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

np.dot(x, y)
x.dot(y)

# compare the result with Exercise 1.3.3

array([[19, 22],
       [43, 50]])

array([[19, 22],
       [43, 50]])

In [23]:
# Exercise 1.3.4:  Elementwise division

print (x / y)
print (np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
# Exercise 1.3.5:  Elementwise square/square root/log/...
x = np.array([[1,2],[3,4]])
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [115]:
x=np.array([[1,4],[1,2],[3,2]])
y=np.array([[2,3,4],[2,3,1]])
x.dot(y)

array([[10, 15,  8],
       [ 6,  9,  6],
       [10, 15, 14]])

### 1.4. Other useful array functions

- Numpy provides many useful functions for performing computations on arrays
    - **sum/mean/min/max/std**  along different dimensions
    - **transpose**
    - reshape, expand/squeeze dimensions
    - **sort** and **argsort**

In [6]:
# Exercise 1.4.1:  array sum/mean/max/min/std

x = np.array([[1,2],[3,4],[3,5]])
x

# Compute sum of all elements; prints "10"
print ("1. sum of all elements:",np.sum(x))  
# or directly use x.sum()

# Compute sum of each column (dimension 0)
# return 1-dimension array
print ("2. sum of each column:", np.sum(x, axis=0))  
np.sum(x, axis=0, keepdims=True).shape

# Compute sum of each row (dimension 1)
# return 1-dimension array
print ("3. sum of each row:", np.sum(x, axis=1))  

array([[1, 2],
       [3, 4],
       [3, 5]])

1. sum of all elements: 18
2. sum of each column: [ 7 11]


(1, 2)

3. sum of each row: [3 7 8]


In [7]:
# sum on different axis
a = np.array([1, 2, 3])
a1 = a.reshape(3,1)
a2 = a.reshape(1,3) # note the difference with a
a1
a2
a1.sum(axis=0)
a1.sum(axis=1)
a2.sum(axis=0)
a2.sum(axis=1)

array([[1],
       [2],
       [3]])

array([[1, 2, 3]])

array([6])

array([1, 2, 3])

array([1, 2, 3])

array([6])

In [9]:
#  high-rank array sum/mean/max/min/std

a=np.random.randn(4,3,2)

# sum along the last dimension
sum_2=np.sum(a, axis=-1)

# the dimension selected for sum will 
# be removed in the sum
sum_2.shape


# to keep the sum with the same rank?
# use argument keepdims, i.e., np.sum(a, axis=-1, keepdims = True)


(4, 3)

In [10]:
# Exercise 1.4.2:  Array transpose
x = np.array([[1,2],[3,4],[5,6]])
x
print("1. shape of x:", x.shape)
print ("2. transpose of x:", x.T)
print("3. shape of the transpose of x:", x.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

1. shape of x: (3, 2)
2. transpose of x: [[1 3 5]
 [2 4 6]]
3. shape of the transpose of x: (2, 3)


In [11]:
# Exercise 1.4.2:  Array reshape

x = np.array([[1,2],[3,4],[5,6]])

# reshape it to 2x3 matrix
print("1. reshape to 2x3 matrix:", np.reshape(x, (2,3)))
# note that this is different from transpose

# flatten the matrix into 1-dimension array
print ("2. flatten x:", np.reshape(x, -1))

1. reshape to 2x3 matrix: [[1 2 3]
 [4 5 6]]
2. flatten x: [1 2 3 4 5 6]


In [12]:
# Exercise 1.4.3:  Extend/squeeze dimensionality

x = np.array([1,2,3,4])  # rank 1
y = np.array([[1,2,1],[3,4,3]]) # rank 2
x.shape
y.shape

# extend x to have shape (1,4)
x1 = np.expand_dims(x, axis = 0 )
x1.shape


# Any other ways? Try the following:
np.newaxis is None
x[None,:]
x[np.newaxis,:]

# extend x to have shape (4,1)
x[:,None]

# extend y to have shape (2,1,3)
y[:,None,:]

(4,)

(2, 3)

(1, 4)

True

array([[1, 2, 3, 4]])

array([[1, 2, 3, 4]])

array([[1],
       [2],
       [3],
       [4]])

array([[[1, 2, 1]],

       [[3, 4, 3]]])

In [8]:
# Remove single-dimensional entries from the shape of an array

x = np.array([[1,2,3,4]])  # Shape (1,4)
x.shape

np.squeeze(x, axis=0)

(1, 4)

array([1, 2, 3, 4])

In [36]:
# Exercise 1.4.4:  Array sort 

x = np.array([[8,2],[3,4],[5,2]])
x

# sort along the first axis (rows)
np.sort(x, axis=0)

# sort the matrix along the second axis (columns)
# the default value of "axis" is -1, the last axis 
np.sort(x)

# how to sort in descending order?
np.sort(x, axis=0)[::-1]


array([[8, 2],
       [3, 4],
       [5, 2]])

array([[3, 2],
       [5, 2],
       [8, 4]])

array([[2, 8],
       [3, 4],
       [2, 5]])

array([[8, 4],
       [5, 2],
       [3, 2]])

In [14]:
# Exercise 1.4.5:  Array argsort, argmax, argmin

x = np.array([[3,2,5],[3,4,1]])
x
# sort each row and return the **original index of each value**
# in an array of the same shape as x
x1=np.argsort(x,axis=1)
x1

# sort each column
x.argsort(axis=0)

# How can this function be useful?

# how to find the indexes of the smallest/largest 
# value in each row ? 
x1[:,-1]

# how to find the indexes of the largest value in each column?




array([[3, 2, 5],
       [3, 4, 1]])

array([[1, 0, 2],
       [2, 0, 1]])

array([[0, 0, 1],
       [1, 1, 0]])

array([2, 1])

array([[0, 0, 1],
       [1, 1, 0]])

In [19]:
# Exercise 1.4.6: Term-Frequency Matrix:
# each row is a document
# each column is a word. 
# Suppose words are w_0, w_1, w_2, w_3, w_4
# value at [i,j] is the count of word j 
# in document i

tf=np.array([[0,5,0,1,2], [1,0,4,0,2], [0,2,3,1,2]])
tf

# 1. Count total occurrences of each word
np.sum(tf, axis=0)

# 2. Find the length of each document
np.sum(tf, axis=1)

# 3. Fill the term-frequency matrix 
#    with binary values (1: present, 0: not present)
b1=np.where(tf>0,1,0)
b1

# 4. count document frequency of each word 
#    i.e. the number of documents that contain the word
np.sum(b1,axis=0)

# 5. Find the most frequent word in each document
tf.argmax(axis=1)
np.argsort(tf,axis=1)[:,-1]


array([[0, 5, 0, 1, 2],
       [1, 0, 4, 0, 2],
       [0, 2, 3, 1, 2]])

array([1, 7, 7, 2, 6])

array([8, 7, 8])

array([[0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1]])

array([1, 2, 2, 2, 3])

### 1.5. Broadcasting
- Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations
- Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
- Example - Normalization:
    - subtract each samples by mean vector
    - divide each sample row by feature std vector (1-dimension array)  
- It would be very inefficient to use a loop to achieve this given a large matrix


In [56]:
# Exercise 1.5.1:  Successful broadcasting

# Add the vector B to each row of A

import time

A = np.random.random((10000,4))
B = np.array([10,6,8,5])
A.shape
B.shape
print("1. 1st row before addition ", A[0])

# By loop:
start=time.time()   # get starting time
for row in A:
    row+=B
print("2. time used: %.4f ms"%(time.time()-start))

print("3. 1st row after addition ", A[0])

(10000, 4)

(4,)

1. 1st row before addition  [0.14675589 0.09233859 0.18626021 0.34556073]
2. time used: 0.0306 ms
3. 1st row after addition  [10.14675589  6.09233859  8.18626021  5.34556073]


In [57]:
# By Broadcasting
# Notice the time used is much smaller than the previous approach

A = np.random.random((10000,4))
B = np.array([10,6,8,5])
A.shape
B.shape
print("1. 1st row before addition ", A[0])

start=time.time()
A = A + B
print("2. time used: %.4f ms"%(time.time()-start))

print("3. 1st row after addition ", A[0])

(10000, 4)

(4,)

1. 1st row before addition  [0.14824068 0.00778736 0.83495657 0.43588383]
2. time used: 0.0004 ms
3. 1st row after addition  [10.14824068  6.00778736  8.83495657  5.43588383]


In [95]:
# Exercise 1.5.2:  Failed broadcasting

# Add a vector to each column of A
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([1, 0, 1, 4])
Z = A + B
print (Z)


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

### 1.6. Broadcasting Rules:
1. Assume two arrays A and B. 
   - <font color='blue'>For example, A has size(10000, 4), B has size (4,). A has rank 2, and B has rank 1</font>
2. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
    - <font color='blue'>Padding 1 to the left of the shape of B. So B's shape becomes (1,4)</font>
3. The two arrays are said to be **compatible** in a dimension **if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension**. If compatible, continue to Step 4; otherwise stop and raise an error
    
    - Compare the shapes of A and B in each dimension: 
        * <font color='blue'>Dimension 1: A is 10000 and B is 1 => compatible </font>   
        * <font color='blue'> Dimension 2: A is 4 and B is 4 => compatible</font> 
    - <font color='blue'> So, A and B are compatible in every dimension</font>
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    - <font color='blue'> After brodcasting, B's shape => (10000,4)</font>
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
    - <font color='blue'> Suppose B=([1, 0, 1]). After broadcasting, B => [ [1, 0, 1],[1, 0, 1],... ]</font>
6. Apply array math using B after broadcasting

In [10]:
# Exercise 1.5.3:  revisit Exercise 1.5.3

# Add a vector to each column of A
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([1, 0, 1, 4])
A.T
B

# A's shape (4,3), B's shape (1,4)
# It's incompatible with A at the 2nd dimension

# However, after transpose A
# they are compatible
Z = A.T + B  
Z


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

array([1, 0, 1, 4])

array([[ 2,  4,  8, 14],
       [ 3,  5,  9, 15],
       [ 4,  6, 10, 16]])

## 2. Sparse Matrix
- Why sparse matrix
    * In some matrixes (e.g. document-term matrix), most of the elements are zero. These matrices are called **sparse matrices**, while the ones that have mostly non-zero elements are called **dense matrices**.
    * These matrixes usually are very big. It needs memory to store every number
- Sparse matrix: a matrix that **only stores non-zero elements**. 
- Scipy package provides different types of sparse matrix. Commonly used types:
    * csc_matrix: Compressed Sparse Column format
    * csr_matrix: Compressed Sparse Row format
- Sparse matrixes can be manipulated almost in the same way as a dense matrix. Check https://docs.scipy.org/doc/scipy/reference/sparse.html for functions for sparse matrixes.

In [69]:
# Exercise 2.1: Define a sparse matrix

import numpy as np
from scipy.sparse import csr_matrix
A = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 5]])
print("1. \n", A)
print("2. ", A[2,1])
A.shape

1. 
   (0, 0)	1
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
2.  0


(3, 3)

In [72]:
# Exercise 2.2: Sparse matrix math

A = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 5]])
v = np.array([1, 0, -1])
A.dot(v)

array([ 1, -3, -1], dtype=int64)